# Generated by Django 2.2.2 on 2019-06-22 10:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("slug", models.SlugField()),
                ("events_url", models.URLField()),
                ("timezone", timezone_field.fields.TimeZoneField()),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("url", models.URLField(unique=True)),
                ("image_url", models.URLField()),
                ("start_at", models.DateTimeField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="rough_trade_calendar.Location",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
