# Generated by Django 2.2.7 on 2019-11-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rough_trade_calendar", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="detail_html",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="youtube_id",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
