# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/rough-trade-calendar
    docker:
      - image: circleci/python:3.7
        environment:
          DATABASE_URL: postgresql://rough_trade_calendar:security_is_important@localhost/rough_trade_calendar
          DATABASE_NO_SSL_REQUIRE: True
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: rough_trade_calendar
          POSTGRES_PASSWORD: security_is_important
          POSTGRES_DB: rough_trade_calendar

    environment:
      SECRET_KEY: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt-get -y install libenchant1c2a
            sudo pip install pipenv
            pipenv install --dev

      - run:
          name: run tests
          command: pipenv run pytest

      - run:
          name: deployment check
          command: pipenv run python manage.py check --deploy --fail-level INFO

      - run:
          name: check code formatting
          command: |
            pipenv run isort --check-only
            pipenv run black --check --diff .
            find . -iname "*.py" | xargs pipenv run pylint

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: tr1
